# Generated by Django 3.2.12 on 2022-03-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_prfile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='prfile_pic',
            new_name='profile_pic',
        ),
    ]
