# Generated by Django 3.2.12 on 2022-03-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220315_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_orders',
            field=models.IntegerField(null=True),
        ),
    ]
