# Generated by Django 3.2.12 on 2022-03-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_order_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='total_orders',
            new_name='customer_orders',
        ),
    ]
